### ISSUE TITLE
Method not found: Serilog.AppSettingsLoggerConfigurationExtensions.AppSettings

### ISSUE THREAD

**Issue by Vrlwrox** [serilog/serilog-settings-appsettings#10]
My project references `Serilog.Settings.AppSettings` version `2.0.0`. It also references another assembly that references the same version of `Serilog.Settings.AppSettings`. When I update my project to use `Serilog.Settings.AppSettings` version `2.1.0` I get the following exception when reading configuration:

> Method not found: 'Serilog.LoggerConfiguration Serilog.AppSettingsLoggerConfigurationExtensions.AppSettings(Serilog.Configuration.LoggerSettingsConfiguration, System.String)'.

Note, I only update my project and not the other assembly (there the version stays at 2.0.0). Also, the other assembly is the one calling `.ReadFrom.AppSettings()`.

Looking through code, I can see this is a result of adding an extra optional parameter to `Serilog.LoggerConfiguration Serilog.AppSettingsLoggerConfigurationExtensions.AppSettings` method.

```csharp
// 2.0.0
public static LoggerConfiguration AppSettings(this LoggerSettingsConfiguration settingConfiguration, string settingPrefix = null);

// 2.0.1
public static LoggerConfiguration AppSettings(this LoggerSettingsConfiguration settingConfiguration, string settingPrefix = null, string filePath = null);
```

**Comment by khellang** [comment]
This is the biggest issue when adding optional parameters to a method: it's always a binary breaking change. When the assembly calling the method is compiled, the default value is "burned" into the assembly, so when you add a new parameter to a method, you have to recompile all other assemblies that calls that method. It's unfortunate that this was done in a patch release, though.

**Comment by nblumhardt** [comment]
Ah, no good - I have a feeling I'd meant to bump the major version on this one but missed it.

I think we should add an overload with the old signature so that 2.1 is compatible with clients compiled against both the old and new versions.

**Comment by Vrlwrox** [comment]
@nblumhardt, yes, this should easily be fixed by adding overloads. I propose three overloads with 0, 1 and 2 string parameters. This way you keep compatibility with 2.0 and 2.1.

**Comment by nblumhardt** [comment]
@Vrlwrox thanks for the follow-up. I think we can get by with just the two overloads, the current and previous signatures (marking the old one non-editor-browsable).

**Comment by nblumhardt** [comment]
Hi @Vrlwrox - 2.1.1-dev is now on NuGet with the fix, any chance you can check it out to see whether your situation is resolved correctly? Cheers!

**Comment by Vrlwrox** [comment]
Yes, it's fixed.

**Comment by nblumhardt** [comment]
Thanks @Vrlwrox! #12 on the way.
