### ISSUE TITLE
Upgrade to Serilog.Settings.AppSettings v2.1.1 breaks calls to `.ReadFrom.AppSettings()`

### ISSUE THREAD

**Issue by tsimbalar** [serilog/serilog-settings-appsettings#13]
I think it is related to the changes from #10 and #12 

The following code no longer compiles after upgrading from **v2.1.0** to **v2.1.1**

``` c#
    public class LogConfig
    {
        static public void Configure()
        {
            var loggerConfiguration = new LoggerConfiguration().ReadFrom.AppSettings();
            Log.Logger = loggerConfiguration.CreateLogger();
        }
    }
```

![image](https://user-images.githubusercontent.com/160544/30578286-59b833f8-9d13-11e7-9176-874b3a670194.png)

``` text
Error	CS0121	The call is ambiguous between the following methods or properties: 'AppSettingsLoggerConfigurationExtensions.AppSettings(LoggerSettingsConfiguration, string)' and 'AppSettingsLoggerConfigurationExtensions.AppSettings(LoggerSettingsConfiguration, string, string)'
```

I guess probably only one of the overloads should have optional params.

**Comment by nblumhardt** [comment]
D'oh! Swapped a binary-breaking change for a source-breaking one :-(

Thanks for the heads-up, I'll push a fix straight through...

...and after that I'm taking a short holiday from shipping patches :-)

**Comment by nblumhardt** [comment]
2.1.2 should have it covered.

**Comment by tsimbalar** [comment]
Confirmed, works like a charm :)
