### ISSUE TITLE
Custom Params

### ISSUE THREAD

**Issue by spati2** [serilog/serilog-settings-appsettings#17]
Hi,
I wanted to set some custom parameters on the App.config. Something along the lines of 

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:LiterateConsole" value="AWS.Logger.SeriLogger" />
    <add key="serilog:write-to:LiterateConsole"/>
    <add key="serilog:CustomParam" value="Custom" />
    </appSettings>
</configuration>

Is there a way I could access this custom param when I read the configs from the appsettings?

**Comment by merbla** [comment]
@spati2 do you have some example code?

**Comment by spati2** [comment]
My plan was to read the code as such 
var config = new LoggerConfiguration().
                ReadFrom.AppSettings();
But the custom key value pair do not show up in the config

**Comment by tsimbalar** [comment]
I think we'll need more to go further on that issue.

I'll close it ... Feel free to re-open if needed.
