### ISSUE TITLE
Allow logging level configuration per source in AppSettings configuration

### ISSUE THREAD

**Issue by paulomorgado** [serilog/serilog-settings-appsettings#18]
(as per requested in #7)

Something like:

    <add key="serilog:source-log-level:somesource" value="Verbose" />
    <add key="serilog:source-log-level-switch:somesource" value="Switch1" />

**Comment by tsimbalar** [comment]
I'm not sure about what you mean when saying "per source" , but if you are talking about *source context* as in : `Logger.ForContext<MyClass>()` ... then, that feature is called *[MinimumLevel.Override()](https://nblumhardt.com/2016/07/serilog-2-minimumlevel-override/)*.

The *static* case has been covered by `ReadFrom.AppSettings()` for a while by #2 , and it looks like this : (taken from https://github.com/serilog/serilog-settings-appsettings#adding-minimum-level-overrides ) : 
```xml
    <add key="serilog:minimum-level" value="Information" />
    <add key="serilog:minimum-level:override:Microsoft" value="Warning" />
    <add key="serilog:minimum-level:override:Microsoft.AspNetCore.Mvc" value="Error" />
```

The *dynamic* case (with level switches) has not been merged to the `master` branch yet, but has been implemented by serilog/serilog#1020 . I believe it will be part of Serilog v2.6+, and it would look like this : 

```xml
    <add key="serilog:level-switch:$specificSwitch" value="Warning" />
    <add key="serilog:minimum-level:override:Microsoft" value="$specificSwitch" />
```

(see test case https://github.com/serilog/serilog/blob/5bcf1338c36880e2b3c6b5064aab75d55bee6ebd/test/Serilog.Tests/Settings/KeyValuePairSettingsTests.cs#L285 )

**Comment by paulomorgado** [comment]
OOPS!

My bad for not knowing that!

But having an option to use a switch will be great.

**Comment by tsimbalar** [comment]
@paulomorgado no problem :) I guess it needs to be a bit more obvious in the documentation :p
