### ISSUE TITLE
Strong name verification failed

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog-settings-appsettings#28]
It's ok with version 2.1.2

![image](https://user-images.githubusercontent.com/21261007/42883394-33a6e7d4-8aa4-11e8-99ae-b22528449ea9.png)

but with DEV versions above 2.1.2 verification failed

 ![image](https://user-images.githubusercontent.com/21261007/42883501-6fac805e-8aa4-11e8-9065-14a8ce401d5d.png)

and

![image](https://user-images.githubusercontent.com/21261007/42883542-8ab5c040-8aa4-11e8-8989-9b3c149f2352.png)

Now under IIS with shadowCopyBinAssemblies=true (default option) we have error like this https://stackoverflow.com/questions/21763822/how-to-disable-strong-name-verification-for-all-net-assembly/27922861

**Comment by nblumhardt** [comment]
Interesting, sounds like it needs investigation, thanks!

**Comment by Suchiman** [comment]
This issue has been released to nuget with Version `2.2.1` so whoever Upgrades, will run into this issue

**Comment by nblumhardt** [comment]
@Suchiman can you reproduce this, BTW?

**Comment by Suchiman** [comment]
@nblumhardt yes, i've updated the package in my ASP.NET MVC 5 application and immediately ran into https://stackoverflow.com/questions/21763822/how-to-disable-strong-name-verification-for-all-net-assembly/27922861

**Comment by nblumhardt** [comment]
(Unlisted 2.2.1 to try to keep things sane while I narrow this down..)

**Comment by nblumhardt** [comment]
Appears that this was due to the build image not being specified as VS2017 - I made the config change and tested the resulting dev package; releasing from master now.

**Comment by nblumhardt** [comment]
2.2.2 is published: https://github.com/serilog/serilog-settings-appsettings/releases/tag/v2.2.2
