### ISSUE TITLE
How to add ApplicationInsights Details

### ISSUE THREAD

**Issue by laxman4434** [serilog/serilog-settings-appsettings#29]
How to set  the key to when using Serilog.Sinks.ApplicationInsights

Tried this way :

    <add key="serilog:using:ApplicationInsights" value="Serilog.Sinks.ApplicationInsights" />
    <add key="serilog:write-to:ApplicationInsightsEvents" value="<my key value>" />

But that doesn't work.

Any help would be appreciated.

**Comment by MNF** [comment]
It’s better to ask on Stackoverflow or in 
https://github.com/serilog/serilog-sinks-applicationinsights. 
Also often useful to enable SelfLog, as described in 
https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

**Comment by nblumhardt** [comment]
@laxman4434 just guessing from the second link posted by @MNF, you need to specify the parameter name for the instrumentation key:

```

**Comment by nblumhardt** [comment]
See also https://github.com/Suchiman/SerilogAnalyzer, which can generate XML configuration from code :stars:
