### ISSUE TITLE
Use .Net 5 packages?

### ISSUE THREAD

**Issue by zachrybaker** [serilog/serilog-settings-appsettings#49]
Some poor blokes like me need this code to work well with both net472, netCore3.1 and Net5 (and possibly net6) targets.  This package ends up in a large solution and ends up pulling a v4 of System.Configuration.ConfigurationManager.  We have another hard requirement for v5 of this package, however, that keeps an app from booting, unless I overwrite this dll on boot with a v5.

I really doubt that there's a hard requirement on the net472 framework's version, right?

**Comment by nblumhardt** [comment]
Hi @zachrybaker  - would your problem be solved by adding a .NET 5 TFM to https://github.com/serilog/serilog-settings-appsettings/blob/dev/src/Serilog.Settings.AppSettings/Serilog.Settings.AppSettings.csproj ? We've made that change in several other libs so should be no problem pushing through here. Any chance of a PR?

**Comment by zachrybaker** [comment]
I doubt it would in my case only b/c my target is actually netCore3.1.

**Comment by Numpsy** [comment]
Question: What version of ```System.Configuration.ConfigurationManager``` should a Serilog 4 version of this library use for none-framework builds? (e.g. use the minimum version that works / use the latest version / use versions that match the .NET 6/8 TFMs?)

**Comment by nblumhardt** [comment]
I think for this package I'd lean towards "the minimum non-vulnerable version that works", but I haven't given it any deep thought :-)

**Comment by Numpsy** [comment]
Ok (version 5.0 has been deprecated now, so that won't be the one to use at least)

**Comment by Numpsy** [comment]
WIP updates for Serilog 4 at https://github.com/serilog/serilog-settings-appsettings/pull/52 (adds .NET6/8 targets)

**Comment by Numpsy** [comment]
V3 is published and now has these dependencies:
![image](https://github.com/serilog/serilog-settings-appsettings/assets/1178570/a1a45a32-69ba-48a9-a08e-aa710776c23d)
i.e it's using the inbox version of ```System.Configuration.ConfigurationManager``` on .NET Framework, and a 'minimum' version on .NET Standard and Core.
I *believe* that users should be able to bump the reference to version 6 or newer in their own application if they need a newer version.
