### ISSUE TITLE
formatter in web.config is not used with File sink

### ISSUE THREAD

**Issue by zaha** [serilog/serilog-settings-appsettings#6]
Hi,

I'm trying to set the JsonFormatter in my services' web config like so:

```csharp
Log.Logger = new LoggerConfiguration()
    .ReadFrom.AppSettings()
    .Enrich.FromLogContext()
    .CreateLogger();
```

```xml
<add key="serilog:minimum-level" value="Verbose" />
<add key="serilog:using:File" value="Serilog.Sinks.File" />
<add key="serilog:write-to:File" />
<add key="serilog:write-to:File.formatter" value="Serilog.Formatting.Json.JsonFormatter, Serilog" />
<add key="serilog:write-to:File.path" value="C:\test\Logs\Service.log" />
<add key="serilog:write-to:File.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss.fff} {SourceContext}[{Level}] &lt;{RequestId}&gt;: {Message}{NewLine}{Exception}" />
```

But it is not outputting JSON logs. When I do the same via code, it's working just fine:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.File(new JsonFormatter(), @"C:\test\logs\Service.log")
    .CreateLogger();
``` 

I also turned on selflog but it's not logging anything. Am I missing something or is this a bug?

Cheers
Michael

**Comment by zaha** [comment]
Okay, nevermind. I just noticed, that there is **no outputTemplate parameter** when using the formatter parameter. After commenting that out in the web.config, it worked.

Of course, I noticed this only minutes after posting this issue. Before I was looking for a solution myself for almost an hour... ^^'

**Comment by nblumhardt** [comment]
Great! Glad you tracked it down, thanks for following up.
