### ISSUE TITLE
Can you setup filters?

### ISSUE THREAD

**Issue by vmary2014** [serilog/serilog-settings-appsettings#8]
Hi
Using the app or web config files can I set filters too?
For example, I want to display to a console app any log except from a specific namespace.
In code you could do something like this
`.Filter.ByExcluding(Matching.FromSource<MyNameSpace>())`
However I have not found a way to do this using the app settings.
Is it possible to do it?
Thanks
Vincent

**Comment by nblumhardt** [comment]
Hi @vmary2014 - thanks for getting in touch.

I'm short on time this morning to get a proper example to you, sorry, but you might find the XML config example for `Serilog.Filters.Expressions` helpful:

https://github.com/serilog/serilog-filters-expressions#xml-configuration

There's also a ticket here in this repository suggesting we implement minimum level overrides in XML configuration ( #2 ) - which would be the better solution, but has not been completed IIRC.

**Comment by vmary2014** [comment]
Nice one I can't believe I missed that one. I will give it a try.
Thanks for your help.
Vincent.
